name: Comp_gra

run-name: ${{ github.actor }} nadelal polny unitaz koda 🚀

on:  push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code in repository
        uses: actions/checkout@v3
      - name: Install deps
        run: python -m pip install --upgrade pip
      - name: Check Test
        run: python test/test1.py